@localurl = http://localhost:3000
@herokurul = https://discalproyect.herokuapp.com
@url = {{localurl}}

### Get students from class
GET {{url}}/students/classgroup/ZBSI HTTP/1.1
### GET all teachers
GET {{url}}/teachers HTTP/1.1

### GET specific teacher
GET {{url}}/classgroups/teacher/Eli HTTP/1.1

### GET area result
GET {{url}}/areaResult/sesion/6121b6f5234fb600233d3b6e HTTP/1.1

### GET sessions of student
GET {{url}}/sesions/student/yy HTTP/1.1

### POST login de teacher
POST {{url}}/teachers/login
Content-Type: application/json

{
    "userId":"juanita",
    "password":"123"
}

### POST classgroup
POST {{url}}/classgroups
Content-Type: application/json

{
    "name":"classtest",
    "teacher":"juanita"
}

### PATCH sesion
PATCH {{url}}/sesions
Content-Type: application/json

{
    "sesionId":"61266c9fae2a14002418ba8a",
    "estado":true
}